name: Windows x86_64 Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    environment: release
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.7.0
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        modules: qttools

    - name: Install build tools
      shell: powershell
      run: |
        choco install jom -y
        echo "C:\Qt\Tools\QtCreator\bin" >> $env:GITHUB_PATH
        echo "C:\Qt\6.7.0\msvc2019_64\bin" >> $env:GITHUB_PATH

    - name: Build DebugEngine
      shell: cmd
      run: |
        qmake YunYooDbgCore.pro -spec win32-msvc
        jom release

    - name: Build GUI Library
      shell: cmd
      run: |
        cd gui
        qmake x64dbglib.pro -spec win32-clang-msvc
        jom release
        cd ..

    - name: Build A64Dbg
      shell: cmd
      run: |
        qmake A64Dbg.pro -spec win32-clang-msvc
        jom release

    - name: Build VMPStudio
      shell: cmd
      run: |
        qmake VMPStudio.pro -spec win32-clang-msvc
        jom release

    - name: Package artifacts
      shell: powershell
      run: |
        $date = Get-Date -Format "yyyyMMdd"
        Compress-Archive -Path @("A64Dbg/release/*", "VMPStudio/release/*") -DestinationPath "X64Dbg-$date-win64.zip"

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: X64Dbg-*-win64.zip
        draft: false
        prerelease: false
        title: "Nightly Build ${{ github.run_number }}"
        body: "Automatic build for Windows x86_64"
