name: Build Windows Release

on:
  push:
    tags:
      - "v*"  # 通过标签触发构建（例如 v1.0.0）

jobs:
  build:
    runs-on: windows-latest  # Windows 最新环境
    env:
      QT_VERSION: 6.6.0       # 已验证兼容的 Qt 版本
      QT_ARCH: win64_msvc2019_64
      QMAKE_SPEC: win32-clang-msvc
      QT_INSTALL_DIR: D:/Qt   # 显式指定 Qt 安装目录

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Qt 和依赖
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          arch: ${{ env.QT_ARCH }}
          dir: ${{ env.QT_INSTALL_DIR }}  # 强制安装路径
          modules: qtbase qttools qtwinextras  # 必需模块
          install-deps: true  # 自动安装 MSVC 工具链

      - name: 配置 MSVC 环境
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo "PATH=${{ env.QT_INSTALL_DIR }}\${{ env.QT_VERSION }}\msvc2019_64\bin;%PATH%" >> %GITHUB_ENV

      - name: 构建核心库 (YunYooDbgCore)
        shell: cmd
        run: |
          qmake YunYooDbgCore.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake release

      - name: 构建 GUI 库 (x64dbglib)
        shell: cmd
        run: |
          cd gui
          qmake x64dbglib.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake release
          cd ..

      - name: 构建 A64Dbg 主程序
        shell: cmd
        run: |
          qmake A64Dbg.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake release

      - name: 构建 VMPStudio 主程序
        shell: cmd
        run: |
          qmake VMPStudio.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake release

      - name: 打包 Release 文件
        shell: cmd
        run: |
          7z a -r X64Dbg-Windows-Release.zip ^
            ./release/A64Dbg.exe ^
            ./release/VMPStudio.exe ^
            ./release/*.dll ^
            ./release/platforms/

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: X64Dbg-Windows-Release
          path: X64Dbg-Windows-Release.zip

      - name: 发布到 GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: X64Dbg-Windows-Release.zip
