name: Build Windows Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    env:
      QT_VERSION: 6.6.0
      QT_ARCH: win64_msvc2022      # 修正后的有效架构名称
      QT_INSTALL_DIR: C:/Qt        # 使用默认安装路径
      QMAKE_SPEC: win32-msvc       # 规范化的 spec 名称

    steps:
      # ========== 1. 代码检出 ==========
      - name: Checkout code
        uses: actions/checkout@v4

      # ========== 2. 安装 Qt 6 ==========
      - name: Install Qt with modules
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          arch: ${{ env.QT_ARCH }}
          dir: ${{ env.QT_INSTALL_DIR }}
          modules: |
            qt6-base
            qt6-tools
            qt6-winextras
            qt6-svg
            qt5compat
          install-deps: true       # 自动安装 MSVC 2022 依赖

      # ========== 3. 配置编译环境 ==========
      - name: Setup MSVC 2022
        shell: cmd
        run: |
          # 使用社区版路径
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          # 设置环境变量
          echo "PATH=${{ env.QT_INSTALL_DIR }}\${{ env.QT_VERSION }}\msvc2022_64\bin;%PATH%" >> %GITHUB_ENV

      # ========== 4. 构建流程 ==========
      - name: Build Core Library
        shell: cmd
        run: |
          qmake YunYooDbgCore.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake clean all

      - name: Build GUI Library
        shell: cmd
        run: |
          cd gui
          qmake x64dbglib.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake clean all
          cd ..

      - name: Build A64Dbg
        shell: cmd
        run: |
          qmake A64Dbg.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake clean all

      - name: Build VMPStudio
        shell: cmd
        run: |
          qmake VMPStudio.pro -spec ${{ env.QMAKE_SPEC }} CONFIG+=release
          nmake clean all

      # ========== 5. 打包与上传 ==========
      - name: Package Release
        shell: cmd
        run: |
          7z a -r X64Dbg-Windows-Release.zip ^
            ./release/A64Dbg.exe ^
            ./release/VMPStudio.exe ^
            ./release/*.dll ^
            ./release/platforms/ ^
            ./release/translations/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: X64Dbg-Windows-Release
          path: X64Dbg-Windows-Release.zip

      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: X64Dbg-Windows-Release.zip
